# Generated by Django 3.1 on 2020-12-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=150)),
                ('mobile_no', models.IntegerField()),
                ('shift', models.CharField(choices=[('day shift', 'Day Shift'), ('night shift', 'Night Shift')], max_length=30)),
                ('specialization', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
            ],
        ),
    ]
