# Generated by Django 3.1 on 2020-12-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('mobile_no', models.IntegerField()),
                ('disease', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=40)),
                ('address', models.TextField()),
            ],
        ),
    ]
